name: Deploy Staging to VPS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploying Develop Branch to Staging VPS
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 10m
          command_timeout: 15m
          script: |
            cd /home/pradana/IELC-CRM
            
            # 1. Pull perubahan terbaru dari branch develop
            git pull origin develop
            
            # 2. Optimasi Laravel
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
